# Generated by Django 5.0.6 on 2024-05-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('mailid', models.CharField(max_length=200)),
                ('state', models.IntegerField()),
                ('district', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('gst', models.CharField(max_length=200)),
            ],
        ),
    ]
