# Generated by Django 5.0.6 on 2024-05-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABS', '0002_state_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ledgername', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('mailid', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('gst', models.IntegerField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('active', models.CharField(max_length=40)),
            ],
        ),
    ]
